### PR TITLE
Split intermittent outcomes into separate `triage` line items

### LINKED ISSUE #48: `triage` should distinguish intermittent `TIMEOUT`s, `CRASH`es, `ERROR`s from permanents

### PR DESCRIPTION
**Pull request by ErichDonGubler**
* Resolves #48.

### CODE REVIEW

File: moz-webgpu-cts/src/main.rs [hunk 1]
```diff
@@ -1047,29 +1146,75 @@ fn run(cli: Cli) -> ExitCode {
...
-    {num_tests_with_failures_somewhere} test(s) with some portion `FAIL`ing, {num_subtests_with_failures_somewhere} subtests total
-    {num_tests_with_timeouts_somewhere} test(s) with some portion returning `TIMEOUT`/`NOTRUN`, {num_subtests_with_timeouts_somewhere} subtests total
+    {num_tests_with_perma_failures_somewhere} test(s) with some portion perma-`FAIL`ing, {num_subtests_with_perma_failures_somewhere} subtests total
+    {num_tests_with_perma_timeouts_somewhere} test(s) with some portion returning permanent `TIMEOUT`/`NOTRUN`, {num_subtests_with_perma_timeouts_somewhere} subtests total
+    {num_tests_with_intermittent_crashes} tests(s) with some portion expecting intermittent `CRASH`
+    {num_tests_with_intermittent_runner_errors} test(s) with execution reporting intermittent `ERROR`
+  LOW PRIORITY:
+    {num_tests_with_intermittent_timeouts_somewhere} test(s) with some portion intermittently returning `TIMEOUT`/`NOTRUN`, {num_subtests_with_intermittent_timeouts_somewhere} subtest(s) total
+    {num_tests_with_intermittent_failures_somewhere} test(s) with some portion intermittently `FAIL`ing, {num_subtests_with_intermittent_failures_somewhere} subtests total
```
Comment (ErichDonGubler) [inline moz-webgpu-cts/src/main.rs:1217]: - [ ] File follow-up work: don't print items with counts of 0 by default.

Comment (ErichDonGubler) [reply moz-webgpu-cts/src/main.rs:1217]: See #66.
